run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - typecheck
    - errcheck
    - gofmt
    - goimports

issues:
  exclude-use-default: false

