name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Build clusterctl
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          EXT=""; if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
          OUT="dist/clusterctl-${GOOS}-${GOARCH}${EXT}"
          go build -o "$OUT" ./cmd/clusterctl
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clusterctl-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/clusterctl-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

